## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
a = np.arange(24)
v = tf.constant([1,22])
s = tf.constant(5)
m = tf.constant(a,shape=[2,12])
t = tf.constant(a,shape=[2,3,4])
v,s,m,t

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 22], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2, 12), dtype=int64, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])>)

2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
v.shape, v.ndim, tf.size(v)
s.shape, s.ndim, tf.size(s)
m.shape, m.ndim, tf.size(m)
t.shape, t.ndim, tf.size(t)

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
t1 = tf.random.uniform(shape=(5,300))
t2 = tf.random.uniform(shape=(5,300))

t1, t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(t1,tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.714005, 80.87825 , 78.328476, 78.259705, 79.130585],
       [70.127075, 72.09944 , 70.1678  , 73.24611 , 74.27739 ],
       [75.16001 , 79.52858 , 76.74643 , 78.14266 , 77.28679 ],
       [77.11357 , 75.401215, 72.79376 , 75.06637 , 75.20651 ],
       [79.87283 , 83.40137 , 78.573715, 79.025894, 81.82093 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(t1,tf.transpose(t2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71398 , 80.878235, 78.3285  , 78.259705, 79.13059 ],
       [70.12709 , 72.09943 , 70.16779 , 73.24608 , 74.277405],
       [75.159996, 79.52858 , 76.74646 , 78.142654, 77.28679 ],
       [77.11355 , 75.401215, 72.79378 , 75.06637 , 75.20653 ],
       [79.87285 , 83.40138 , 78.57374 , 79.025894, 81.82089 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
tf3 = tf.random.uniform(shape=[224,224,3])

7. Find the min and max values of the tensor you created in 6.

In [ ]:
tf.reduce_min(tf3)
tf.reduce_max(tf3)

<tf.Tensor: shape=(), dtype=float32, numpy=1.4781952e-05>

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999968>

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
tf4 = tf.random.uniform(shape=[1,224,224,3])
tf.squeeze(tf4)


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
tf9 = tf.random.uniform(minval=0,maxval=4,shape=[10], dtype='int32')
tf.argmax(tf9)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

10. One-hot encode the tensor you created in 9.

In [ ]:
tf10 = tf.one_hot(tf9,depth=4)
tf10

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)>